# This is the YAML config file to make this a little more abstractish

# Stuff about you.
user_config:
  # Your Name. This will be used for the page title
  name: 'Michael Gerbush'

  # The file you want to parse to be your resume
  # Must be a format supported by github-markup
  file: 'resume.md'

  # A picture of you. Should be a complete url
  pic: 'http://www.gravatar.com/avatar/26b555c864480dccc6f3815932716e52.png'

  # The google analytics key you wish to use.
  gkey: 'UA-31852727-1'

# For github pages to work, this needs to be the GitHub repository this file is
# stored in.
github:
  remote: 'git@github.com:msgerbush/Resume.git'
